### PR TITLE
b2254

### PR DESCRIPTION
**Pull request by Nexesenex**

### CODE REVIEW

**Comment by brokofankone** [comment]
@Nexesenex Could I make a request to you to build a Cublas 12.3 ampere exe for your latest fork? It's still way faster on Ampere, and new LR builds are for sure slower, I don't think this issue was fixed at all. I'm running a single RTX 3070 and in some cases your ampere fork is giving me double speed on the same quant versus latest LR builds with CB 12.4. :/ 

Sadly, I'm having issues building it myself, and tbh I think it would be a net positive for Ampere users to have a reliably-built executable! Thank you for your time and efforts in any case ❤️

**Comment by Nexesenex** [comment]
Ok @brokofankone, I will make my next build on 12.3 instead of 12.4.

Give me your feedback once you test it!

**Comment by brokofankone** [comment]
> Ok @brokofankone, I will make my next build on 12.3 instead of 12.4.
> 
> 
> 
> Give me your feedback once you test it!

Awesome, thank you!!

**Comment by Nexesenex** [comment]
@brokofankone it's online, ready for testing!

**Comment by brokofankone** [comment]
> @brokofankone it's online, ready for testing!

Massive thanks for the build!

But now I'm really confused 😮 

image

Your previous Ampere build is twice as fast on the same quant, same kobold preset, same everything and swiping on the same prompt "Write a story" over and over again. With 9B Q4_K_M and IQ3_XSS I saw no difference between 12.4 (latest lost ruins) and 12.3 (your latest).

But on your old Ampere build, this 11B Q4_K_M quant is way faster, almost twice as fast. On your new Ampere build it's slightly faster, more consistently so than the 12.4 build, however this could also be just a bit of noise, unlike with the old build vs new one. I am not sure what in your previous build is causing this massive improvement now, but it is there and with some quants it's quite pronounced.

Notably, the processing speed with the latest your vs lost ruins looks the same, but on the old one, the blas processing is slower, however it comes out as overall much faster.

**Comment by Nexesenex** [comment]
Well, I might have a little idea about what's up, but I didn't care enough to make tests when I published the last days builds.
Thanks for the Cublas 12.3/12.4 comparison, I'll revert on 12.3 from now on.
As for the main problem, lemme dig a bit in the recent Cuda changes of KoboldCPP.

**Comment by brokofankone** [comment]
> Well, I might have a little idea about what's up, but I didn't care enough to make tests when I published the last days builds. Thanks for the Cublas 12.3/12.4 comparison, I'll revert on 12.3 from now on. As for the main problem, lemme dig a bit in the recent Cuda changes of KoboldCPP.

Thank you for doing the build and looking into it, much appreciated :)) This example above is using one quant to show the improvement, but I had some other cases where I noticed almost x2 speed-up in favor of your old build versus the previous 3 Lost ruins versions, so I would say it's not just a fluke, I've been noticing it for a while. You seem like you have an idea, which gives me a lot of hope ❤️‍🔥

**Comment by Nexesenex** [comment]
Well, I tried my idea, but I can confirm that Lostruins corrected his recent builds.
My "fast builds" deliver the same speed as my current ones, including on the model you tested.
I'm using a Ryzen 5600 and a 3090 right now. I can't figure out why your config behaves so erratically with my various builds.

**Comment by Nexesenex** [comment]
Well, I tried my idea, but it didn't change anything much.
My "fast builds" deliver the same speed as my current ones, including on the model you tested.
I'm using a Ryzen 5600 and a 3090 right now. I can't figure out why your config behaves so erratically with my various builds.

**Comment by Nexesenex** [comment]
Well, I obtain similar results between my old fas builds, my new builds of this month, and whatever I try actually slow things down rather than helping it.
I have also a Ryzen 5xxx and a Geforce 30xx, so I'd suggest you to update your drivers to last version, and beyond that I don't know.
Sorry ! :D

**Comment by Nexesenex** [comment]
Well, I obtain similar results between my old fas builds, my new builds of this month, and whatever I try actually slow things down rather than helping it.
I have also a Ryzen 5xxx and a Geforce 30xx, so I'd suggest you to update your drivers to last version, and beyond that I don't know.

**Comment by brokofankone** [comment]
> Well, I obtain similar results between my old fas builds, my new builds of this month, and whatever I try actually slow things down rather than helping it. I have also a Ryzen 5xxx and a Geforce 30xx, so I'd suggest you to update your drivers to last version, and beyond that I don't know.

Thanks for trying it out! I'll update the studio driver today and see if there is a difference. Do I need to somehow update CUDA seperately from the nvidia studio driver?

**Comment by brokofankone** [comment]
@Nexesenex 

Updated the Nvidia Studio driver (I think it was one release behind), and updated the CUDA Toolkit to 12.4.

Same results, the old 1.59 build is x2 faster (getting 14-17 t/s on the new ones and up to 27-30t/s on the old one with the q4 11b quant).

I think I might just stay on the old build for specific ("trusted") quants, it's just too much of a gain ultimately. I guess if you aren't seeing any difference at all then it may be some weird quirk with my system setup. 

Thanks a ton for helping out, the new build and your testing! 🙏 

Could this be... a gguf arc thing? Because my quant here is reported as llama (since the solar builds are technically based on llama arc at the lowest level). Maybe Mistral is not affected by this because the 9B I use for testing all are mistral. The 11B is a solar-based merge reported as llama.

**Comment by Nexesenex** [comment]
On KCPP Bench, I reach PP 1000t/s TG 45 t/s on both 1.59 and 1.62 builds at 8k context on your model fully offloaded.
And TG 55t/s at 2k context.
More precisely, 1.59d is broadly 2% faster in generation, and 3% slower in PP than 1.62x, both in Cublas 12.3.
There might be a thing, because these slight differences repeat, but it doesn't affect at all my experience.
And there's so many conflicts now between the old commits and the new ones that I can't sort this out, and it might just be related to deeper change in LlamaCPP rather than on LostRuins's modifs.
Be sure to check if there are no MMQ argument in your command line, which might have been ignored in 1.59 and used in 1.62, and your huge perf differences make me think about either MMQ activation (slower than non-MMQ execution on Ampere starting with/beyond batch size 32), either about row split being used instead of layers which are best for Ampere (but that's for multi-GPU, it should not affect you).

**Comment by brokofankone** [comment]
Thanks again for trying this out. I am leaning towards some type of llama change that causes this, I was sure it was Cublas 12.3 as it was about Ampere and that's what I'm using, but now it seems like that's not really the case. 

As for MMQ, I cannot run K-quants without it. MMQ apparently has its own quirks like that, and it makes quants like IQ faster but on Q4_K_M it will not even start outputting at all, so these tests I have been doing are both with it turned on.

**Comment by Nexesenex** [comment]
You're welcome.
I digged out my 16 march internal compile, see if it can help.

**Pull request merged**
